export enum SpinnerType {
  BallPulse = "BallPulse",
  BallGridPulse = "BallGridPulse",
  BallClipRotate = "BallClipRotate",
  SquareSpin = "SquareSpin",
  BallClipRotatePulse = "BallClipRotatePulse",
  BallClipRotateMultiple = "BallClipRotateMultiple",
  BallPulseRise = "BallPulseRise",
  BallRotate = "BallRotate",
  CubeTransition = "CubeTransition",
  BallZigZag = "BallZigZag",
  BallZigZagDeflect = "BallZigZagDeflect",
  BallTrianglePath = "BallTrianglePath",
  BallScale = "BallScale",
  LineScale = "LineScale",
  LineScaleParty = "LineScaleParty",
  BallScaleMultiple = "BallScaleMultiple",
  BallPulseSync = "BallPulseSync",
  BallBeat = "BallBeat",
  LineScalePulseOut = "LineScalePulseOut",
  LineScalePulseOutRapid = "LineScalePulseOutRapid",
  BallScaleRipple = "BallScaleRipple",
  BallScaleRippleMultiple = "BallScaleRippleMultiple",
  BallSpinFadeLoader = "BallSpinFadeLoader",
  LineSpinFadeLoader = "LineSpinFadeLoader",
  TriangleSkewSpin = "TriangleSkewSpin",
  Pacman = "Pacman",
  BallGridBeat = "BallGridBeat",
  SemiCircleSpin = "SemiCircleSpin",
  BallRotateChase = "BallRotateChase",
  Orbit = "Orbit",
  AudioEqualizer = "AudioEqualizer",
  CircleStrokeSpin = "CircleStrokeSpin",
  BallDoubleBounce = "BallDoubleBounce",
}

export type SpinnerKey = keyof typeof SpinnerType;

export type SpinnerValue = `${SpinnerType}`;
